### ISSUE TITLE
python2下安装失败

### ISSUE THREAD

**Issue by m358807551** [mouday/chinesename#5]
```
(venv) myp:170818_test_all $ pip install chinesename
Looking in indexes: http://mirrors.aliyun.com/pypi/simple/
Collecting chinesename
  Downloading http://mirrors.aliyun.com/pypi/packages/7f/9b/c527e661ca3530bfbc65b4702ca055d58e2d3e11039631627b7ea01a45fe/chinesename-0.0.9.tar.gz (150kB)
    100% |████████████████████████████████| 153kB 2.1MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/4w/rwy1x5nj16d2t2tbtcs385pc0000gn/T/pip-install-9NGiPN/chinesename/setup.py", line 16, in <module>
        md_to_rst("README.md", "README.rst")
      File "/private/var/folders/4w/rwy1x5nj16d2t2tbtcs385pc0000gn/T/pip-install-9NGiPN/chinesename/setup.py", line 10, in md_to_rst
        files={'input_files[]':open(from_file,'rb')})
    IOError: [Errno 2] No such file or directory: 'README.md'

```

**Comment by mouday** [comment]
已经在修复了 chinesename-0.1.0
```
(py2) $ pip install chinesename -i https://pypi.python.org/simple/
Looking in indexes: https://pypi.python.org/simple/
Collecting chinesename
  Using cached https://files.pythonhosted.org/packages/f8/e7/954e5297033c5a64a7c822fb0e1b08b30d639a0432e2f5052b2a1cf05c67/chinesename-0.1.0-py2-none-any.whl
Installing collected packages: chinesename
Successfully installed chinesename-0.1.0
```
